### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Seluj78** [erichschroeter/cmake-auto-increment-build-number#1]
Hi,

I'd be really interested in using your cmake auto increment tho I can't get it to work... How do you implement it ?

**Comment by cpipero** [comment]
It took me a few minutes to figure out (for the C example), I think a simple README would do.

When you build the project first, it creates a "generate" program that you have to run with the desired options to spit out the content of what will become the file "version.h", which is declared in the "main.c" file (which just stdout's the version info).

Not really a build number automation script, just an example of auto-incrementing...
